apiVersion: v1
kind: Secret
metadata:
  name: nodeapp
type: Opaque
data:
   MYSQL_USER: {{ .Values.secret.MYSQL_USER| b64enc | quote }}
   MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD| b64enc | quote }}
   MYSQL_DATABASE: {{ .Values.secret.MYSQL_DATABASE| b64enc | quote }}


 