apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-assessment-02.fullname" . }}--mysql
  labels:
    {{- include "devops-assessment-02.labels" . | nindent 4 }}
    app: mysql
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devops-assessment-02.selectorLabels" . | nindent 6 }}
      app: mysql
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devops-assessment-02.selectorLabels" . | nindent 8 }}
        app: mysql
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
     
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3307
              protocol: TCP
          #volumeMounts:
           #   - name: db
            #    mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
               name: mysql
  