apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "devops-assessment-02.labels" . | nindent 4 }}
    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devops-assessment-02.selectorLabels" . | nindent 4 }}
    app: mysql
